theme: jekyll-theme-minimal
title: Maxim Mai
show_downloads: false
#logo: /assets/img/logo.png


social:
  name: Joe Bloggs
  links:
    - https://twitter.com/username
    - https://plus.google.com/u/0/+username
- https://www.facebook.com/username
